"""empty message

Revision ID: 22f20b5db484
Revises:
Create Date: 2025-04-07 15:53:12.310081

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "22f20b5db484"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchange",
        sa.Column("token", sa.UUID(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "CANCELED", "FAILED", "FINISHED", name="exchangestatus"),
            nullable=False,
        ),
        sa.Column("user_token", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("exchange")
    # ### end Alembic commands ###
