services:
  pbb_database:
    container_name: pbb_database
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    user: postgres
    volumes:
      - pbb_database_volume:/var/lib/postgresql/data
    env_file:
      - ./env/.env.database
    networks:
      - pbb_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "pbbdb"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  pbb_database_volume:
    name: pbb_database_volume
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./volumes/postgres/data

networks:
  pbb_network:
    name: pbb_network