"""empty message

Revision ID: 8b9990ed7109
Revises:
Create Date: 2025-03-30 14:11:35.183052

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8b9990ed7109"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchange",
        sa.Column("token", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ACTIVE", "CANCELED", "FAILED", "FINISHED", name="exchangestatus"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_table(
        "exchange_user",
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("exchange_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exchange_id"],
            ["exchange.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("exchange_user")
    op.drop_table("exchange")
    # ### end Alembic commands ###
